batch_size: 1024
#training_len: 1800
training_len: 18
use_normalize: True
drop_out: 0.1
model_infos: {}

#exclude_cols: [11, 12, 19, 20, 26]
exclude_cols: []

#input_dim: 27
input_dim: 15
nb_epochs: 5000
#n_class: 7
n_class: 4
log_interval: 200
test_interval: 1000

#hidden_dims: [128, 64, 32]
hidden_dims: [32, 16]

learning_rate: 0.0005